development:
  adapter: mysql2
  database: opennotes
  username: root
  password: hello_-s
  host: 192.168.1.93
production:
  adapter: postgresql
  database: d22s6r0mv2ui8d
  username: ughyidtukrrigk
  password: WRa9upVWBPM9tsMDAiK7feYBKB
  host: ec2-54-228-195-91.eu-west-1.compute.amazonaws.com